import type { GetServerSidePropsContext, NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "src/components/ui/dialog";
import { Button } from "src/components/ui/button";
import { ssgHelper } from "src/utils/ssg";
import { api } from "src/utils/api";
import Link from "next/link";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "src/components/ui/card";

const Home: NextPage = () => {
  const utils = api.useContext();
  const { data: session } = useSession();
  const user = utils.auth.getUserSession.getData();

  return (
    <>
      <Head>
        <title>Stark</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col gap-12 p-4">
        <nav className="flex items-center justify-between">
          <div className="text-2xl font-extrabold uppercase md:text-4xl">
            Stark
          </div>
          <Dialog>
            <DialogTrigger asChild>
              <Button>{session ? "Account" : "Get Started"}</Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
              <DialogHeader>
                <DialogTitle>{session ? "Account" : "Sign In"}</DialogTitle>
                <DialogDescription>
                  {session ? "Time to Get Healthy" : "Join Stark with Discord"}
                </DialogDescription>
              </DialogHeader>
              {session ? (
                <div className="flex flex-col justify-center gap-4">
                  <h3 className="self-center">Signed in as: {user?.name}</h3>
                  <Link href="/dashboard">
                    <Button className="w-full">Dashboard</Button>
                  </Link>
                  <Button
                    variant="destructive"
                    onClick={() =>
                      void signOut({
                        callbackUrl: "/",
                      })
                    }
                  >
                    Sign Out
                  </Button>
                </div>
              ) : (
                <div className="flex flex-col justify-center gap-4">
                  <Button
                    onClick={() =>
                      void signIn("discord", {
                        callbackUrl: "/dashboard",
                      })
                    }
                  >
                    Discord
                  </Button>
                  <Button
                    onClick={() =>
                      void signIn("google", {
                        callbackUrl: "/dashboard",
                      })
                    }
                  >
                    Google
                  </Button>
                </div>
              )}
            </DialogContent>
          </Dialog>
        </nav>

        <Card>
          <CardHeader>
            <CardTitle>Simple, Easy, Stay Healthy, Get Strong</CardTitle>
            <CardDescription>Your Ultimate Fitness Solution</CardDescription>
          </CardHeader>
          <CardContent>
            With Stark, you can customize your workout routine based on your
            fitness level, preferences, and goals. Whether you want to lose
            weight, build muscle, or simply stay in shape, our app has a variety
            of workouts that are tailored to meet your needs. Whether you{`'`}re
            a beginner or an experienced fitness enthusiast, Stark is the
            perfect tool to help you achieve your fitness goals and live a
            healthier, happier life. Let{`'`}s get started!
          </CardContent>
          <CardFooter>
            <Button className="w-full font-bold">Start For Free</Button>
          </CardFooter>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>A Managed Approach To Fitness</CardTitle>
          </CardHeader>
          <CardContent>
            We understand that staying motivated can be challenging, so we
            {`'`}ve incorporated a variety of features to help you stay on
            track. From progress tracking to personalized reminders, our app is
            designed to make your fitness journey fun, easy, and rewarding.
          </CardContent>
          <CardFooter>
            <Button className="w-full font-bold">Read More</Button>
          </CardFooter>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>The Core Values We Live By</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 gap-2 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Innovation</CardTitle>
                <CardDescription>
                  We believe in constantly pushing the boundaries of what{`'`}s
                  possible and developing new and innovative ways to help our
                  users get fit and healthy.
                </CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Accessibility</CardTitle>
                <CardDescription>
                  We believe that fitness should be accessible to everyone,
                  regardless of their background or fitness level. That{`'`}s
                  why we
                  {`'`}ve designed our app to be user-friendly and customizable
                  for all.
                </CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Accessibility</CardTitle>
                <CardDescription>
                  We believe that fitness should be accessible to everyone,
                  regardless of their background or fitness level. That{`'`}s
                  why we
                  {`'`}ve designed our app to be user-friendly and customizable
                  for all.
                </CardDescription>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Community</CardTitle>
                <CardDescription>
                  We believe that fitness is a journey that{`'`}s better when
                  shared. Our app fosters a sense of community and support among
                  our users, allowing them to motivate and inspire one another.
                </CardDescription>
              </CardHeader>
            </Card>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>
              Achieve Your Fitness Goals With Our Customizable Workouts
            </CardTitle>
          </CardHeader>
          <CardContent>
            Customizable workouts are a crucial aspect of any effective fitness
            program, and at Stark, we understand that everyone has unique
            fitness goals, preferences, and needs. That{`'`}s why our app offers
            a variety of customizable workouts to help you tailor your fitness
            routine to meet your individual needs. Our app includes a wide range
            of exercises and workouts, ranging from cardio to strength training,
            yoga, and Pilates, and more. Whether you{`'`}re a beginner or an
            experienced fitness enthusiast, our app has workouts to meet your
            needs. With FitTrack, you can customize your workouts based on your
            fitness level, goals, and available equipment. Our app allows you to
            choose from a variety of exercise options, select the duration of
            your workout, and set your own pace and intensity.
          </CardContent>
          <CardFooter>
            <Button className="w-full font-bold">Read More</Button>
          </CardFooter>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>
              Incredible Features To Help You Stay Motivated
            </CardTitle>
          </CardHeader>
          <CardContent>
            At Stark, we believe that fitness is a journey that{`'`}s better
            when shared. That{`'`}s why we offer a feature that allows you to
            follow other users on our app and connect with a community of
            like-minded individuals who are on a similar fitness journey.
            Following other users on FitTrack is simple and easy. You can search
            for other users based on their fitness goals, interests, and
            location, and follow them with just a click of a button. Once you
            {`'`}re connected, you can see their progress updates, offer support
            and encouragement, and share your own progress updates.
          </CardContent>
          <CardFooter>
            <Button className="w-full font-bold">Read More</Button>
          </CardFooter>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Need More, Premium Features With Stark Pro</CardTitle>
          </CardHeader>
          <CardContent>
            At Stark, we offer a premium membership that includes a variety of
            features designed to help you achieve your fitness goals more
            effectively. Two of these features include the ability to copy
            workouts and view chart progress. With our premium membership, you
            can easily copy workouts created by other users or trainers on our
            app. This feature allows you to discover new workouts and routines
            that have been tried and tested by others, and integrate them into
            your own fitness program. You can also save your favorite workouts
            for easy access later. In addition, our premium membership allows
            you to view your progress in a visual and easy-to-understand chart
            format. This feature helps you to see your progress over time, track
            your fitness journey, and stay motivated as you work towards your
            goals. By viewing your progress in chart format, you can identify
            areas where you{`'`}re making progress and areas where you need to
            focus more attention. You can also set goals and benchmarks for
            yourself, and track your progress towards these goals over time.
          </CardContent>
          <CardFooter>
            <Button className="w-full font-bold">Read More</Button>
          </CardFooter>
        </Card>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const { ssg, session } = await ssgHelper(context);

  if (session && session.user) {
    await ssg.auth.getUserSession.prefetch();

    return {
      props: {
        trpcState: ssg.dehydrate(),
      },
    };
  } else {
    return {
      props: {
        trpcState: ssg.dehydrate(),
      },
    };
  }
};
