import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";

import { AspectRatio } from "src/components/ui/aspect-ratio";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Stark</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col gap-12 p-4">
        <nav className="flex items-center justify-between">
          <div className="text-2xl font-extrabold uppercase text-sky-500 md:text-4xl">
            Stark
          </div>
          <div className="custom-button font-bold">Get Started</div>
        </nav>

        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <p className="text-sm md:text-base">
              Simple, Easy, Web Hosting - 10x Faster
            </p>
            <h1 className="text-lg font-semibold md:text-xl">
              Your Managed Cloud Hosting Platform
            </h1>
            <p>
              Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
              sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit
              amet, qui minim labore adipisicing minim sint cillum sint
              consectetur cupidatat.
            </p>
            <div className="custom-button w-32 font-bold">Start For Free</div>
          </div>
          <AspectRatio
            ratio={16 / 9}
            className="mx-auto h-64 w-64 md:h-80 md:w-80"
          >
            <Image
              src="/assets/exercise-1.webp"
              fill
              className="object-cover"
              alt="Exercise 1"
            />
          </AspectRatio>
        </div>

        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <p className="text-sm md:text-base">About Us</p>
            <h3 className="text-lg font-semibold md:text-xl">
              A Managed Cloud Hosting Platform Where Teams Can Build
            </h3>
            <p>
              Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
              sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit
              amet, qui minim labore adipisicing minim sint cillum sint
              consectetur cupidatat.
            </p>
            <div className="custom-button w-32 font-bold">Read More</div>
          </div>

          <AspectRatio
            ratio={16 / 9}
            className="mx-auto h-64 w-64 md:h-80 md:w-80"
          >
            <Image
              src="/assets/exercise-2.webp"
              fill
              className="object-cover"
              alt="Exercise 2"
            />
          </AspectRatio>
        </div>

        <div className="flex flex-col gap-4 rounded bg-sky-100 p-4">
          <h2>The Core Values We Live By</h2>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div className="ga-4 flex flex-col">
              <h3>Innovative At Heart</h3>
              <p>
                Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
                sint cillum sint consectetur cupidatat.
              </p>
            </div>
            <div className="ga-4 flex flex-col">
              <h3>Data Drive Ideology</h3>
              <p>
                Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
                sint cillum sint consectetur cupidatat.
              </p>
            </div>
            <div className="ga-4 flex flex-col">
              <h3>Simpliciy in Everything</h3>
              <p>
                Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
                sint cillum sint consectetur cupidatat.
              </p>
            </div>
            <div className="ga-4 flex flex-col">
              <h3>Win As A Team</h3>
              <p>
                Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
                sint cillum sint consectetur cupidatat.
              </p>
            </div>
          </div>
        </div>

        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <h3 className="text-lg font-semibold md:text-xl">
              Have Complete Peace Of Mind with Our Free Migration
            </h3>
            <p>
              Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
              sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit
              amet, qui minim labore adipisicing minim sint cillum sint
              consectetur cupidatat.
            </p>
            <div className="custom-button w-32 font-bold">Read More</div>
          </div>

          <AspectRatio
            ratio={16 / 9}
            className="mx-auto h-64 w-64 md:h-80 md:w-80"
          >
            <Image
              src="/assets/exercise-3.webp"
              fill
              className="object-cover"
              alt="Exercise 3"
            />
          </AspectRatio>
        </div>

        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2">
            <h3 className="text-lg font-semibold md:text-xl">
              Have Complete Peace Of Mind with Our Free Migration
            </h3>
            <p>
              Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
              sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit
              amet, qui minim labore adipisicing minim sint cillum sint
              consectetur cupidatat.
            </p>
            <div className="custom-button w-32 font-bold">Read More</div>
          </div>

          <AspectRatio
            ratio={16 / 9}
            className="mx-auto h-64 w-64 md:h-80 md:w-80"
          >
            <Image
              src="/assets/exercise-4.webp"
              fill
              className="object-cover"
              alt="Exercise 4"
            />
          </AspectRatio>
        </div>

        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-2 rounded bg-sky-100 p-4">
            <h3 className="text-lg font-semibold md:text-xl">
              Have Complete Peace Of Mind with Our Free Migration
            </h3>
            <p>
              Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
              sint cillum sint consectetur cupidatat. Lorem ipsum dolor sit
              amet, qui minim labore adipisicing minim sint cillum sint
              consectetur cupidatat.
            </p>
            <div className="custom-button w-32 font-bold">Read More</div>
          </div>
          <div className="flex flex-col items-center justify-center gap-4 p-4">
            <h3>
              Stark changes my life, save me thousands of hours, and made
              working out a dream
            </h3>
            <p>
              Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
              sint cillum sint consectetur cupidatat.
            </p>
            <div className="flex items-center gap-4">
              <Image
                src="https://github.com/shadcn.png"
                alt="Avatar"
                className="rounded"
                width={100}
                height={100}
              />
              <div className="flex flex-col gap-2">
                <h4>User Name</h4>
                <p>
                  Lorem ipsum dolor sit amet, qui minim labore adipisicing minim
                  sint cillum sint consectetur cupidatat.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="mx-auto flex items-center justify-center gap-4 p-4 bg-sky-100">
        <p>Product</p>
        <p>Quick Links</p>
        <p>Source</p>
        <p>Support</p>
      </footer>
    </>
  );
};

export default Home;
